name: bmm_cnn
channels:
  - defaults
dependencies:
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - functools32=3.2.3.2
  - futures=3.2.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.1
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - linecache2=1.0.0
  - matplotlib=2.2.3
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.24.1
  - pcre=8.42
  - pip=19.0.1
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=2.7.15
  - python-dateutil=2.7.5
  - pytz=2018.9
  - qt=5.9.7
  - readline=7.0
  - setuptools=40.8.0
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - subprocess32=3.5.3
  - tk=8.6.8
  - tornado=5.1.1
  - traceback2=1.4.0
  - unittest2=1.1.0
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - keras==1.0.7
    - pyyaml==3.13
    - scipy==1.2.1
    - theano==1.0.4

